-- ============================================================
-- Competition system
-- ============================================================
-- Three parallel competitions per league:
--   campionato   — fixed head-to-head schedule (round-robin)
--   battle_royale — every team vs every other team each matchday
--   coppa         — configurable cup (knockout / group+knockout)
--
-- Common source of truth: published_team_scores (not JSON blobs).
-- Scoring is configured per competition via scoring_config jsonb.
-- ============================================================

-- ---- Enums --------------------------------------------------

CREATE TYPE competition_type   AS ENUM ('campionato', 'battle_royale', 'coppa');
CREATE TYPE competition_status AS ENUM ('setup', 'active', 'completed', 'cancelled');
CREATE TYPE round_status       AS ENUM ('pending', 'computed', 'locked');
CREATE TYPE fixture_result     AS ENUM ('home_win', 'away_win', 'draw');

-- ---- competitions ------------------------------------------
-- scoring_config jsonb shape (method: 'goal_thresholds'):
--   { "method": "goal_thresholds",
--     "thresholds": [{"min":0,"goals":0},{"min":60,"goals":1}, ...],
--     "points": {"win":3,"draw":1,"loss":0} }
-- scoring_config jsonb shape (method: 'direct_comparison'):
--   { "method": "direct_comparison",
--     "points": {"win":3,"draw":1,"loss":0} }
--
-- tiebreaker_config: ordered array of field names, e.g.:
--   ["points","goal_difference","goals_for","total_fantavoto"]
--
-- coppa_config (coppa type only):
--   { "format": "knockout", "legs": 1, "third_place_match": false }
--   { "format": "group_knockout", "group_count": 2,
--     "teams_per_group": 4, "teams_advancing_per_group": 2,
--     "knockout_legs": 1, "third_place_match": false }
-- --------------------------------------------------------

CREATE TABLE competitions (
  id                uuid               PRIMARY KEY DEFAULT gen_random_uuid(),
  league_id         uuid               NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  name              text               NOT NULL,
  type              competition_type   NOT NULL,
  status            competition_status NOT NULL DEFAULT 'setup',
  season            text,
  scoring_config    jsonb              NOT NULL DEFAULT '{}',
  tiebreaker_config jsonb              NOT NULL
    DEFAULT '["points","goal_difference","goals_for","total_fantavoto"]',
  coppa_config      jsonb,
  created_by        uuid               REFERENCES profiles(id),
  created_at        timestamptz        NOT NULL DEFAULT now()
);

CREATE INDEX idx_competitions_league ON competitions (league_id);

-- ---- competition_teams -------------------------------------
-- Enrollment: which fantasy teams participate in a competition.
-- group_label: 'A', 'B', ... for Coppa group stage assignments.
-- seed: bracket seeding order for Coppa knockout draw.
-- --------------------------------------------------------

CREATE TABLE competition_teams (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  team_id        uuid NOT NULL REFERENCES fantasy_teams(id) ON DELETE CASCADE,
  group_label    text,
  seed           int,
  UNIQUE (competition_id, team_id)
);

CREATE INDEX idx_competition_teams_comp ON competition_teams (competition_id);
CREATE INDEX idx_competition_teams_team ON competition_teams (team_id);

-- ---- competition_rounds ------------------------------------
-- One row per competition round.
-- Campionato / Battle Royale: one round = one matchday.
-- Coppa: one round = one bracket stage round (matchday nullable until linked).
-- phase: 'regular' for Campionato/BR;
--   'group' | 'round_of_32' | 'round_of_16' | 'quarter_final' |
--   'semi_final' | 'third_place' | 'final' for Coppa.
-- --------------------------------------------------------

CREATE TABLE competition_rounds (
  id             uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid         NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  round_number   int          NOT NULL,
  name           text         NOT NULL,
  matchday_id    uuid         REFERENCES matchdays(id),
  phase          text         NOT NULL DEFAULT 'regular',
  status         round_status NOT NULL DEFAULT 'pending',
  computed_at    timestamptz,
  UNIQUE (competition_id, round_number)
);

CREATE INDEX idx_competition_rounds_comp     ON competition_rounds (competition_id);
CREATE INDEX idx_competition_rounds_matchday ON competition_rounds (matchday_id);

-- ---- competition_fixtures ----------------------------------
-- Explicit matchup rows for every competition type.
-- Campionato / Coppa: pre-generated by admin schedule/draw actions.
-- Battle Royale: auto-generated at compute time (N*(N-1)/2 per round).
--
-- home_score / away_score: fantasy goals (null for direct_comparison).
-- result / home_points / away_points: set at compute time.
-- --------------------------------------------------------

CREATE TABLE competition_fixtures (
  id             uuid           PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid           NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  round_id       uuid           NOT NULL REFERENCES competition_rounds(id) ON DELETE CASCADE,
  home_team_id   uuid           NOT NULL REFERENCES fantasy_teams(id),
  away_team_id   uuid           NOT NULL REFERENCES fantasy_teams(id),
  home_fantavoto numeric(8,3),
  away_fantavoto numeric(8,3),
  home_score     int,
  away_score     int,
  result         fixture_result,
  home_points    int,
  away_points    int,
  computed_at    timestamptz,
  UNIQUE (round_id, home_team_id, away_team_id)
);

CREATE INDEX idx_competition_fixtures_round     ON competition_fixtures (round_id);
CREATE INDEX idx_competition_fixtures_comp      ON competition_fixtures (competition_id);
CREATE INDEX idx_competition_fixtures_home      ON competition_fixtures (home_team_id);
CREATE INDEX idx_competition_fixtures_away      ON competition_fixtures (away_team_id);

-- ---- RLS ---------------------------------------------------

ALTER TABLE competitions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE competition_teams    ENABLE ROW LEVEL SECURITY;
ALTER TABLE competition_rounds   ENABLE ROW LEVEL SECURITY;
ALTER TABLE competition_fixtures ENABLE ROW LEVEL SECURITY;

-- Read: any league member
CREATE POLICY "competitions_read"
  ON competitions FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM league_users lu
      WHERE lu.league_id = competitions.league_id
        AND lu.user_id = auth.uid()
    )
  );

CREATE POLICY "competition_teams_read"
  ON competition_teams FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM competitions c
      JOIN league_users lu ON lu.league_id = c.league_id
      WHERE c.id = competition_teams.competition_id
        AND lu.user_id = auth.uid()
    )
  );

CREATE POLICY "competition_rounds_read"
  ON competition_rounds FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM competitions c
      JOIN league_users lu ON lu.league_id = c.league_id
      WHERE c.id = competition_rounds.competition_id
        AND lu.user_id = auth.uid()
    )
  );

CREATE POLICY "competition_fixtures_read"
  ON competition_fixtures FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM competitions c
      JOIN league_users lu ON lu.league_id = c.league_id
      WHERE c.id = competition_fixtures.competition_id
        AND lu.user_id = auth.uid()
    )
  );

-- Write: league_admin only
CREATE POLICY "competitions_admin_all"
  ON competitions FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM league_users lu
      WHERE lu.league_id = competitions.league_id
        AND lu.user_id = auth.uid()
        AND lu.role = 'league_admin'
    )
  );

CREATE POLICY "competition_teams_admin_all"
  ON competition_teams FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM competitions c
      JOIN league_users lu ON lu.league_id = c.league_id
      WHERE c.id = competition_teams.competition_id
        AND lu.user_id = auth.uid()
        AND lu.role = 'league_admin'
    )
  );

CREATE POLICY "competition_rounds_admin_all"
  ON competition_rounds FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM competitions c
      JOIN league_users lu ON lu.league_id = c.league_id
      WHERE c.id = competition_rounds.competition_id
        AND lu.user_id = auth.uid()
        AND lu.role = 'league_admin'
    )
  );

CREATE POLICY "competition_fixtures_admin_all"
  ON competition_fixtures FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM competitions c
      JOIN league_users lu ON lu.league_id = c.league_id
      WHERE c.id = competition_fixtures.competition_id
        AND lu.user_id = auth.uid()
        AND lu.role = 'league_admin'
    )
  );
